### PR TITLE
Replace Google API with feedr

### PR DESCRIPTION
**Pull request by sdepold**
As the Google Feed API is deprecated it will be necessary at some point
to replace it with something else. I wrote
[feedr](https://github.com/sdepold/feedr) which is a drop-in
replacement for the Google Feed API and which is now used.

This PR addresses: #61, #34 (partially)

It will also make it possible in the future to add support for currently not working feeds.

### CODE REVIEW

**Comment by sdepold** [comment]
pinging @eanbowman

**Comment by eanbowman** [comment]
This is wonderful news. I can test it on my end.

I have a working solution on my end which was mentioned in my previous comments, but I'm more than willing to help test your fixes.

**Comment by eanbowman** [comment]
Just  a semantic point more than anything, shouldn't an error log use console.error instead of console.log? Or is it more of a warning?

      error: function () {
        console.log('jQuery RSS: url doesn\'t link to RSS-Feed');
      },

It seems like an error state to me since the feed won't work if the URL is not RSS. Is that correct?

**Comment by sdepold** [comment]
that makes quite a lot of sense to me :)

**Comment by eanbowman** [comment]
I deleted the comment about the error logs because I saw you used throwing
errors in your fixes.

I was a bit confused by GitHub actually.

My mistake! :3

*‬‭‮‪*

*Ean Bowman*


*345 Dufferin St, Unit 820, Toronto, ON*



*M6K 3G1‫‬‭eanbowman@gmail.com <eanbowman@gmail.com>Mobile: (647) 781 8024*

‮҉.

**Comment by sdepold** [comment]
Tests are green. Unfortunately there are no tests for offset. Will need to add those and add support in feedr

**Comment by sdepold** [comment]
Just noticed that offsets are calculated in jquery-rss and not on the server side (-: I'd appreciate if you could run some tests with this branch

**Comment by sdepold** [comment]
So I'm going to merge this PR and release a new major version of this lib.

**Pull request merged**
