### PR TITLE
Make Moment.js optional. Resolves #54.

### LINKED ISSUE #54: Make moment dependency optional
As-is, jquery-rss cannot run without the moment date library introduced with https://github.com/sdepold/jquery-rss/pull/43.

Can the moment dependency be made optional? Not everyone uses Bower to manage dependencies; the date formatting is not desirable for all use-cases.

See also #23

### PR DESCRIPTION
**Pull request by Aurif3x**
See #54. I have attempted to make Moment.js optional.
There are now three options for date formatting:
* Include Moment.js, just like before.
* Do not include Moment.js, and instead provide a custom function, dateFormatFunction(date), which formats dates in whatever way you choose.
* Do not include Moment.js, and do not format dates at all. Use them exactly as the RSS feed gives them to you.

Do I need to add tests to spec.js? I might try that later today; have never used Buster.js before. (Note that I _have_ tested my changes, just not with Buster.)

### CODE REVIEW

**Comment by sdepold** [comment]
Like!

**Comment by Aurif3x** [comment]
Sorry for the long wait for tests; I'm still trying to get Buster to run the tests that already exist.
I'm new to having a Mac, so first, I had to get Homebrew, Node, and Buster installed. Now, I'm stuck because the tests don't successfully run. I'm getting ReferenceErrors stating that "expect" is not defined, or that "moment" is not defined, etc.

I'll keep tinkering until I figure out what I'm doing wrong. I'll have new tests.. eventually! :dizzy_face:

**Comment by sdepold** [comment]
Wait. Let me finish my other pr and thinks will be easier.

**Comment by sdepold** [comment]
Additional note: I'm talking about this guy: #59 
It adds gulp and jscs/jshint and will make running the tests way easier

**Comment by sdepold** [comment]
Just merge the PR. You will need phantom installed and then you can just run `npm test` :) Please rebase too.

**Comment by sdepold** [comment]
Did you want to add tests?

**Comment by Aurif3x** [comment]
Hi! Sorry for being so late with wrapping this up; June got a bit hectic.

I have the test suite working (thanks for the nice commit!).
However, now that I've actually taken a closer look at the test suite, I'm not sure what kind of tests I should add for this update I've made. The tests that currently exist seem to focus primarily on the HTML rendering of the feeds, which this doesn't really affect. Also, my impression is that the tests include Moment.js, and I'm not sure how to make them run both with and without (or if it's even necessary at all).

Any ideas?

**Comment by sdepold** [comment]
Thanks for your work. I will think about the tests for this.

**Comment by sdepold** [comment]
Just released 2.0.0

**Comment by Aurif3x** [comment]
Cool! I'm glad it was helpful.
Sorry I didn't come up with useful tests -- I'm unfortunately still new to formalized JS test suites. :grimacing:

**Pull request merged**
